### ISSUE TITLE
Document "userdata" portable configuration folder for Daemon

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/opentabletdriver.github.io#116]
You can put a folder named `userdata` next to the OpenTabletDriver executable (or working directory? investigate) and it'll read configuration from that instead of the default application directory. This does not seem to be documented on the site.

[discord confusion](https://discord.com/channels/615607687467761684/615611007951306863/1071893972018012210)

**Comment by X9VoiD** [comment]
Resolved by #98
