### ISSUE TITLE
Header hierarchy is not obvious at first glance

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/opentabletdriver.github.io#133]
## Problem

Here is an example where it's worse.

![image](https://github.com/OpenTabletDriver/opentabletdriver.github.io/assets/10338031/370ce4ee-0823-4247-85a2-ea6ac6a14cdb)

It kind of makes sense when laid out like this, but if you can only see this:

![image](https://github.com/OpenTabletDriver/opentabletdriver.github.io/assets/10338031/ad3effc3-9cdc-4858-ac5d-8143717a2b0f)

Then it's not clearly visible that Non-fresh Install is not part of the previous sub-section anymore.

## Proposed changes

Add a number before the headings?

![image](https://github.com/OpenTabletDriver/opentabletdriver.github.io/assets/10338031/5c7d55eb-b197-4ec0-8cc3-0c666670d8d9)

However we can't hardcode it in the header since it breaks TOC, anchor-js, and auto-generated ids.

![image](https://github.com/OpenTabletDriver/opentabletdriver.github.io/assets/10338031/647e4d38-74b5-4ebd-b17a-09d786964290)

**Comment by gonX** [comment]
Seems fixed in #136
